### ISSUE TITLE
TEST WORKFLOW: move-tasks-to-in-progress

### ISSUE THREAD

**Issue by travisjupp** [travisjupp/wordgrid-quest#30]
Testing the workflow for moving items from Todo to In Progress with a PR
- Added permissions property to WF

```yaml
permissions:
  contents: read
  issues: write
  pull-requests: write
  project: write
```
